# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf011b0b3a0b191614dc7d1aaf035952c1ab2bc4170cda554ca91ba5fa2131b2b423424b1f12403c1e576f4c4120611bbe03146ce80605ed18119713d45568d0

test:
  secret_key_base: 649ab0437d5861b5ffead6e093ccee0ea99d404745f4cc1392d4a547d42dc4f24cc28cf93d48cb7402ac17614f9e114ec355a0848294f1e3eee3ad680c4436c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
